# Sidebar navigation

- label: '新着嬢情報'
  items:
    - label: '2021/05/21'
      link: /new/2021-05-21
    - label: '2021/05/20'
      link: /new/2021-05-20
    - label: '2021/05/19'
      link: /new/2021-05-19
    - label: '2021/05/15'
      link: /new/2021-05-15
    - label: '2021/05/13'
      link: /new/2021-05-13
    - label: '2021/05/12'
      link: /new/2021-05-12
    - label: '2021/05/11'
      link: /new/2021-05-11

- label: '地域別情報'
  items:
    - label: 新宿・歌舞伎町
      link: /busty/0010
    - label: 新大久保・高田馬場・目白
      link: /busty/0020
    - label: 池袋
      link: /busty/0030
    - label: 大塚・巣鴨
      link: /busty/0040
    - label: 駒込・田端
      link: /busty/0050
    - label: 西日暮里・日暮里・鶯谷
      link: /busty/0060
    - label: 上野・御徒町
      link: /busty/0070
    - label: 秋葉原・神田
      link: /busty/0080
    - label: 東京・有楽町・銀座
      link: /busty/0090
    - label: 新橋
      link: /busty/0100
    - label: 浜松町・田町
      link: /busty/0110
    - label: 品川・五反田
      link: /busty/0120
    - label: 蒲田・大森・大井町
      link: /busty/0121
    - label: 恵比寿・目黒・中目黒
      link: /busty/0130
    - label: 渋谷・原宿・代々木
      link: /busty/0140
    - label: 千駄ヶ谷・信濃町・四ツ谷・市ヶ谷
      link: /busty/0150
    - label: 飯田橋・水道橋・御茶ノ水
      link: /busty/0160
    - label: 錦糸町・亀戸・新小岩
      link: /busty/0170
    - label: 中野・高円寺・吉祥寺・三鷹
      link: /busty/0180
    - label: 国分寺・立川・八王子・東京郊外
      link: /busty/0200
    - label: 赤羽・東十条・王子・板橋
      link: /busty/0210
    - label: 練馬・下赤塚
      link: /busty/0220
    - label: 金町・亀有・北千住・竹ノ塚
      link: /busty/0230
    - label: 門前仲町・東陽町・葛西・南行徳
      link: /busty/0240
    - label: 自由が丘・三軒茶屋・溝の口・武蔵小杉
      link: /busty/0250
    - label: 京王・小田急線沿線
      link: /busty/0260
    - label: 神奈川地区
      link: /busty/0300
    - label: 横浜・桜木町・関内・新横浜
      link: /busty/0310
    - label: 川崎・鶴見
      link: /busty/0320
    - label: 町田・相模原・厚木・大和
      link: /busty/0330
    - label: 千葉地区
      link: /busty/0500
    - label: 市川・本八幡・西船橋・船橋
      link: /busty/0510
    - label: 松戸・新松戸・柏・我孫子
      link: /busty/0520
